version: '3'

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  handler:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: >
      sh -c "sleep 12
      && python -m gunicorn --name url_service -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:8080 main:app"

volumes:
  db: